name: Caller Workflow

on:
  push:
    branches:
      - main  # Change this to the branch you want to trigger the workflow on
  workflow_dispatch:

jobs:
  call-update-readme:
    uses: PepperDash/readme-automation/.github/workflows/update-readme.yml@main
    with:
      target-branch: 'robotdocs'